source 'https://rubygems.org'
ruby "2.1.2"

gem 'sinatra'
gem 'thin'
gem 'haml'
gem 'coffee-script'
gem 'therubyracer'
gem 'json'
gem 'httparty'
gem 'sinatra-assetpack'
gem 'foundation'
gem 'sass', '~> 3.2.19'
gem 'compass'
gem 'instagram'
